max_unseen_druids_to_retrieve: 200

cocina_output:
  success:
    should_output: true
    location: 'log/cocina_output/success/'
  failure:
    should_output: true
    location: 'log/cocina_output/failure/'
